steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/github-cloner'
      - '.'

  # Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/github-cloner'

  # Deploy to Cloud Run with SSH key mounted as a secret
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'github-cloner'
      - '--image'
      - 'gcr.io/$PROJECT_ID/github-cloner'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--set-secrets'
      - '/root/.ssh/id_rsa=github-ssh-key:latest'

images:
  - 'gcr.io/$PROJECT_ID/github-cloner'

options:
  logging: CLOUD_LOGGING_ONLY